### ISSUE TITLE
XS Advanced development - Configure a Space to develop on a tenant database

### ISSUE THREAD

**Issue by karasatishkumar** [SAPDocuments/Tutorials#2269]
I can see we can map multiple databases to a single space. Below are few queries with respect to that.

1. Can we have multiple applications mapped to different database? I have the following configuration to use a schema in database. But I can not see any configurations to map database and schema.

```
- name: container-3
    type: com.sap.xs.hdi-container
    properties:
      container-name: ${service-name}
    parameters: 
     service-name: container-3
     config:
       schema: SCHEMA_3
```
2. What is the use of multiple database for a single space? Is there a way to specify the db name in mta.yaml?
