### ISSUE TITLE
Use JPA in Custom Logic

### ISSUE THREAD

**Issue by MaximilienFourmyBeyond** [SAPDocuments/Tutorials#3577]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-05-using-jpa.html

Step 4: Change the runtime from Tomcat to TomEE
I got an error in my mta.yaml file during the build because I copy-and-pasted the following code from the tutorial:
```
requires:
    - name: bookshop-hdi-container
      properties:
         JBP_CONFIG_RESOURCE_CONFIGURATION: '[tomee/webapps/ROOT/WEB-INF/resources.xml:
            {"service_name_for_DefaultDB" : "~{hdi-container-name}"}]'
   properties:
      TARGET_RUNTIME: tomee
      buildpack: sap_java_buildpack
```

But in my case, when I generated the project, the resource name is not bookshop-hdi-container but bookshop-db-hdi-container.

To reproduce, you just need to create from a template:
![image](https://user-images.githubusercontent.com/14924866/58604955-39d34b80-8264-11e9-8352-c40f1a515c9d.png)
click on Next
Project name: bookshoptest
click on Next
click on Next
click on Finish

Open the mta.yaml file and the resource name contains the -db-
```
resources:
  - name: bookshoptest-db-hdi-container
```
