### ISSUE TITLE
Unable to deploy to XSA DEV space

### ISSUE THREAD

**Issue by ferrydjaja** [SAPDocuments/Tutorials#3665]
Hi,
I need some help on this. I am creating the mta app that interact with other hdi-container. I created my app hdbsynonym for the other hdi-container and as well as local.hdbsynonym. I am able to run and execute the DB, NodeJS and Web module without issue. 

The problem is when deploying to XSA DEV space. I got the error message: "(DeploymentToXSA) Deployment of the "zearn_srvui" project to XSA failed.(Response state is FAILED)" immediately. 

I am using SAP Web IDE HANA On Premise (SAP Web IDE for HANA 2 - SPS 03 Patch 63 ( Build 4.3.63 )).

From the SAP HANA XS Advanced Cockpit, I can't find the app that was failed to deploy, so I can't provide the log information.

Here is my mta.yaml file:
```
ID: zearn_srvui
_schema-version: '2.1'
version: 0.0.1
modules:
  - name: zearn_srvui-db
    type: hdb
    path: db
    parameters:
      memory: 256M
      disk-quota: 256M
    requires:
      - name: zearn_srvui-hdi-container
        properties:
          TARGET_CONTAINER: '~{hdi-container-name}'
      - name: zearn-container-service
        group: SERVICE_REPLACEMENTS
        properties:
          key: zearnServiceName
          service: '~{the-service-name}'
  
  - name: zearn_srvui-srv
    type: nodejs
    path: srv
    parameters:
      memory: 512M
      disk-quota: 256M
    provides:
      - name: srv_api
        properties:
          url: '${default-url}'
    requires:
      - name: zearnpfe-uaa
      - name: zearn_srvui-db
      - name: zearn_srvui-hdi-container

  - name: zearn_srvui-ui
    type: html5
    path: web
    requires:
      - name: zearnpfe-uaa
      - name: zearn_srvui-ui5
      - name: srv_api
        group: destinations
        properties:
          name: srv_api
          url: '~{url}'
          forwardAuthToken: true
resources:
  - name: zearn_srvui-hdi-container
    properties:
      hdi-container-name: '${service-name}'
    type: com.sap.xs.hdi-container
  - name: zearn-container-service
    parameters:
      service-name: zearn_db-hdi-container
    properties:
      the-service-name: '${service-name}'
    type: org.cloudfoundry.existing-service
  - name: zearnpfe-uaa
    type: com.sap.xs.uaa
    parameters:
      path: ./xs-security.json
  - name: zearn_srvui-ui5
    type: org.cloudfoundry.managed-service
    parameters:
      service: sapui5_sb
      service-plan: sapui5-1.52
```

.hdbgrants in cfg folder:
```
{
  "zearnServiceName": {
    "object_owner" : {
      "container_roles":["consumption", "admin#"]
    },
    "application_user" : {
      "container_roles":["consumption"]
    }
  }
}
```

.hdbsynonymconfig in cfg folder:
```
{
  "ZEARN_ALIAS": {
    "target": {
      "object": "ZEARN_ALIAS",
      "*.configure" : "zearnServiceName"
    }
  },
  "ZEARN_APPLICATIONS": {
    "target": {
      "object": "ZEARN_APPLICATIONS",
      "*.configure" : "zearnServiceName"
    }
  }
}
```
and app hdbsynonym:
```
{
  "ZEARN_ALIAS": {
    "target": {
      "object": "ZEARN_ALIAS"
    }
  },
  "ZEARN_APPLICATIONS": {
    "target": {
      "object": "ZEARN_APPLICATIONS"
    }
  }
}
```

I believe something is missing when I deploy to XSA, but I cannot figure it out further.
