### ISSUE TITLE
Set Up the Manage Rules Project Application

### ISSUE THREAD

**Issue by ceedee666** [SAPDocuments/Tutorials#5230]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-businessrules03-setup-mrp.html

In step 3 the screenshots do not show how to specify a custom business rules service. It would be better if the screenshot would show a complete example.

The following MTA worked for me.

```yaml
ID: businessruleseditor
_schema-version: '2.1'
parameters:
  deploy_mode: html5-repo
version: 0.0.1
modules:
  - name: businessruleseditor_appRouter
    type: approuter.nodejs
    path: businessruleseditor_appRouter
    parameters:
      disk-quota: 256M
      memory: 256M
    requires:
      - name: businessruleseditor_html5_repo_runtime
      - name: businessrules_uaa
      - name: scp-business-rules-trial
resources:
  - name: businessruleseditor_html5_repo_runtime
    parameters:
      service-plan: app-runtime
      service: html5-apps-repo
    type: org.cloudfoundry.managed-service
  - name: businessrules_uaa
    type: com.sap.xs.uaa
    parameters:
      config:
        xsappname: businessrules_uaa-appname
        tenant-mode: dedicated
        role-templates:
          - name: UaaUser
            description: Role template for accessing SAP Business Rule APIs.Editor via user token flow
            scope-references:
              - uaa.user
  - name: scp-business-rules-trial
    type: org.cloudfoundry.existing-service
    parameters:
      service: business-rules
      service-plan: lite
```
