### ISSUE TITLE
Set Up and Generate a New SAP Fiori App Project

### ISSUE THREAD

**Issue by brahammittal** [SAPDocuments/Tutorials#5572]
Tutorial URL: https://developers.sap.com/tutorials/fiori-tools-generate-project.html

Please specify the step you are referring to

npm start

Behind the proxy the setup does not work. We faced the same during the beta testig. You should publish what all needs to be done behind proxy specifically

**Comment by brahammittal** [comment]
Presently I am getting below log from npm start
npm start

> project1@0.0.1 start C:\BrahamLEarn\project1
> ui5 serve --open test/flpSandbox.html#masterDetail-display --

info server:ux-proxy Proxy started for http://services.odata.org
info server:ux-proxy Proxy started for https://ui5.sap.com      
info server:liveload Livereload middleware started for port 35729 and path webapp
Server started
URL: http://localhost:8080
info server:ux-proxy /test-resources/sap/ushell/bootstrap/sandbox.js
info server:ux-proxy /resources/sap-ui-core.js
Error: self signed certificate in certificate chain     
    at TLSSocket.onConnectSecure (_tls_wrap.js:1473:34) 
    at TLSSocket.emit (events.js:311:20)
    at TLSSocket._finishInit (_tls_wrap.js:916:8)       
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:686:12)
Error: self signed certificate in certificate chain     
    at TLSSocket.onConnectSecure (_tls_wrap.js:1473:34) 
    at TLSSocket.emit (events.js:311:20)
    at TLSSocket._finishInit (_tls_wrap.js:916:8)       
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:686:12)
info server:ux-proxy /resources/sap-ui-core.js
Error: self signed certificate in certificate chain     
    at TLSSocket.onConnectSecure (_tls_wrap.js:1473:34) 
    at TLSSocket.emit (events.js:311:20)
    at TLSSocket._finishInit (_tls_wrap.js:916:8)       
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:686:12)

**Comment by tobiasqueck** [comment]
Hi @brahammittal,

Could you please try setting `ignoreCertError: true` in your configuration like in the snippet below and check again? This is not a good practice but I would like to narrow down the issue you are seeing.
```
customMiddleware:
    - name: fiori-tools-proxy
      afterMiddleware: compression
      configuration:
        ignoreCertError: true
        backend:
          - path: /sap
            url: http://services.odata.org
            scp: true 
        ui5:
          path:
            - /resources
            - /test-resources
          url: https://ui5.sap.com
```
