### ISSUE TITLE
Deploy Your Business Application to Cloud Foundry

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#6014]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-cap-deploy-app.html

Step 3: Deploy your application to Cloud Foundry

This step will not work on SAP CP Trial as the default configuration adds the service hana and not hanatrial:

```YAML
 - name: bookshop-db
# ------------------------------------------------------------
   type: com.sap.xs.hdi-container
   parameters:
     service: hana  # or 'hanatrial' on trial landscapes
     service-plan: hdi-shared
   properties:
     hdi-service-name: ${service-name}
```

It would be good to mention that and advise the person following the tutorial to adjust that setting when using SAP CP Trial.
